# "Regression Model - Draft"

> "Using fast.ai and Pytorch's modules, building a regression model and Neural Network using Kaggle's titanic survival data set"

- toc: true
- branch: master
- comments : False
- author : Eric Vincent
- categories : [fastpages, jupyter]

In [77]:
import pandas as pd
import numpy as np


In [78]:
df = pd.read_csv('/kaggle/input/titanic-survival-dataset/train.csv')

In [79]:
df = df.drop(columns=['Name', 'Cabin', 'Ticket', 'PassengerId'])

In [80]:
df['Male'] = df['Sex']

In [81]:
df['Male'] = df['Male'].replace({'male': 1, 'female' : 0})

In [82]:
df['Embarked_C'] = df['Embarked']
df['Embarked_C'] = df['Embarked_C'].replace({'S':0, 'C':1})
df['Embarked_S'] = df['Embarked']
df['Embarked_S'] = df['Embarked_S'].replace({'S':1, 'C':0})
df['Pclass1'] = df['Pclass']
df['Pclass2'] = df['Pclass']
df['Pclass3'] = df['Pclass']
df['Pclass1'] = df['Pclass1'].replace({2:0, 3:0})
df['Pclass2'] = df['Pclass2'].replace({1:0, 3:0, 2:1})
df['Pclass3'] = df['Pclass3'].replace({1:0, 2:0, 3:1})

In [83]:
random_parameters = np.random.rand(1,10)

In [84]:
Sibsp, Parch, Age, log_fare, Pclass1, Pclass2, EmbarkS, EmbarkC, Male, Const = [num for num in random_parameters[0]]

In [85]:
maxAge, maxFare = max(df['Age']), max(df['Fare'])

In [86]:
df['Age_N'] = df['Age'] / maxAge

In [87]:
df['log_Fare'] = df['Fare'] / maxFare

In [88]:
df['log_Fare'] = np.log10(df['log_Fare'] + 1)

In [89]:
parameters = {
    Sibsp, Parch, Age, log_fare, Pclass1, Pclass2, EmbarkS, EmbarkC, Male, Const
    
    
}

In [90]:
df['Ones'] = 1

In [91]:
#collapse-hide
parameters = np.array([0.023121551427445874,
 0.13402581877095354,
 0.1460823666152794,
 0.22088891772092012,
 0.594795670221624,
 0.7961562768917094,
 0.8530100056367039,
 0.8613248152275507,
 0.8901214376590094,
 0.9785782868782011])

In [92]:
model_df = df

In [93]:
model_df = model_df.drop(columns=['Survived', 'Sex', 'Age', 'Fare', 'Embarked'])

In [94]:
model_df = model_df.drop(columns=['Pclass'])

In [95]:
model_df['Age_N'] = model_df['Age_N'].fillna(0)


In [96]:
model_df.isnull().values.any()

True

In [97]:
model_df = model_df.drop(columns=['Pclass3'])

In [98]:
model_df['Embarked_S'] = model_df['Embarked_S'].replace({'Q': 0})
model_df['Embarked_C'] = model_df['Embarked_C'].replace({'Q': 0})
model_df['Linear'] = model_df.dot(parameters)

In [99]:
model_df['Survived'] = df['Survived']

In [100]:
model_df['Loss'] = (model_df['Linear'] - 1)**2

In [101]:
model_df['Linear'].mean()

2.255390616421957

In [102]:
survived_label = model_df['Survived'] == 1
death_label = model_df['Survived'] == 0

In [103]:
survived = model_df.loc[survived_label]
death = model_df.loc[death_label]

In [104]:
#hide
pip install fastbook

Note: you may need to restart the kernel to use updated packages.


In [105]:
import fastbook
fastbook.setup_book()
from fastai.vision.all import *
from fastbook import *

matplotlib.rc('image', cmap='Greys')

In [106]:
death

SibSp  Parch  Male  Embarked_C  Embarked_S  Pclass1  Pclass2   Age_N  \
0        1      0     1         0.0         1.0        0        0  0.2750   
4        0      0     1         0.0         1.0        0        0  0.4375   
5        0      0     1         0.0         0.0        0        0  0.0000   
6        0      0     1         0.0         1.0        1        0  0.6750   
7        3      1     1         0.0         1.0        0        0  0.0250   
..     ...    ...   ...         ...         ...      ...      ...     ...   
884      0      0     1         0.0         1.0        0        0  0.3125   
885      0      5     0         0.0         0.0        0        0  0.4875   
886      0      0     1         0.0         1.0        0        1  0.3375   
888      1      2     0         0.0         1.0        0        0  0.0000   
890      0      0     1         0.0         0.0        0        0  0.4000   

     log_Fare  Ones    Linear  Survived      Loss  
0    0.006103     1  1.984874         0  0.969977  
4    0.006771     1  2.102313         0  1.215093  
5    0.007111     1  1.130991         0  0.017159  
6    0.041878     1  3.134283         0  4.555164  
7    0.017507     1  1.959964         0  0.921530  
..        ...   ...       ...       ...       ...  
884  0.005935     1  1.993904         0  0.987844  
885  0.024013     1  2.089977         0  1.188051  
886  0.010882     1  2.872850         0  3.507568  
888  0.019437     1  1.881848         0  0.777656  
890  0.006520     1  1.474995         0  0.225620  

[549 rows x 13 columns]

In [107]:
survived

SibSp  Parch  Male  Embarked_C  Embarked_S  Pclass1  Pclass2   Age_N  \
1        1      0     0         1.0         0.0        1        0  0.4750   
2        0      0     0         0.0         1.0        0        0  0.3250   
3        1      0     0         0.0         1.0        1        0  0.4375   
8        0      2     0         0.0         1.0        0        0  0.3375   
9        1      0     0         1.0         0.0        0        1  0.1750   
..     ...    ...   ...         ...         ...      ...      ...     ...   
875      0      0     0         1.0         0.0        0        0  0.1875   
879      0      1     0         1.0         0.0        1        0  0.7000   
880      0      1     0         0.0         1.0        0        1  0.3125   
887      0      0     0         0.0         1.0        1        0  0.2375   
889      0      0     1         1.0         0.0        1        0  0.3250   

     log_Fare  Ones    Linear  Survived      Loss  
1    0.056575     1  2.478233         1  2.185174  
2    0.006666     1  1.859239         1  0.738291  
3    0.042829     1  2.807605         1  3.267434  
8    0.009336     1  2.140433         1  1.300588  
9    0.024771     1  2.248379         1  1.558451  
..        ...   ...       ...       ...       ...  
875  0.006082     1  1.366379         1  0.134234  
879  0.065324     1  2.790723         1  3.206687  
880  0.021499     1  2.848710         1  3.417730  
887  0.024714     1  2.596093         1  2.547514  
889  0.024714     1  2.443635         1  2.084081  

[342 rows x 13 columns]

In [108]:
a = np.array([survived.iloc[0]])
surv = tensor(a)
surv

tensor([[1.0000, 0.0000, 0.0000, 1.0000, 0.0000, 1.0000, 0.0000, 0.4750, 0.0566, 1.0000, 2.4782, 1.0000, 2.1852]])

In [109]:
b = tensor([survived.iloc[0]])
b
# TODO list comprehension for the stacked tensor containing all the rows, the result should be #rows, yaxis, xaxis
# do it on the copy df

tensor([[1.0000, 0.0000, 0.0000, 1.0000, 0.0000, 1.0000, 0.0000, 0.4750, 0.0566, 1.0000, 2.4782, 1.0000, 2.1852]])

In [110]:
#collapse-hide
survived

SibSp  Parch  Male  Embarked_C  Embarked_S  Pclass1  Pclass2   Age_N  \
1        1      0     0         1.0         0.0        1        0  0.4750   
2        0      0     0         0.0         1.0        0        0  0.3250   
3        1      0     0         0.0         1.0        1        0  0.4375   
8        0      2     0         0.0         1.0        0        0  0.3375   
9        1      0     0         1.0         0.0        0        1  0.1750   
..     ...    ...   ...         ...         ...      ...      ...     ...   
875      0      0     0         1.0         0.0        0        0  0.1875   
879      0      1     0         1.0         0.0        1        0  0.7000   
880      0      1     0         0.0         1.0        0        1  0.3125   
887      0      0     0         0.0         1.0        1        0  0.2375   
889      0      0     1         1.0         0.0        1        0  0.3250   

     log_Fare  Ones    Linear  Survived      Loss  
1    0.056575     1  2.478233         1  2.185174  
2    0.006666     1  1.859239         1  0.738291  
3    0.042829     1  2.807605         1  3.267434  
8    0.009336     1  2.140433         1  1.300588  
9    0.024771     1  2.248379         1  1.558451  
..        ...   ...       ...       ...       ...  
875  0.006082     1  1.366379         1  0.134234  
879  0.065324     1  2.790723         1  3.206687  
880  0.021499     1  2.848710         1  3.417730  
887  0.024714     1  2.596093         1  2.547514  
889  0.024714     1  2.443635         1  2.084081  

[342 rows x 13 columns]

In [112]:
survived_tensor

tensor([[1.0000, 0.0000, 0.0000,  ..., 2.4782, 1.0000, 2.1852],
        [0.0000, 0.0000, 0.0000,  ..., 1.8592, 1.0000, 0.7383],
        [1.0000, 0.0000, 0.0000,  ..., 2.8076, 1.0000, 3.2674],
        ...,
        [0.0000, 1.0000, 0.0000,  ..., 2.8487, 1.0000, 3.4177],
        [0.0000, 0.0000, 0.0000,  ..., 2.5961, 1.0000, 2.5475],
        [0.0000, 0.0000, 1.0000,  ..., 2.4436, 1.0000, 2.0841]])

In [113]:
len(survived_tensor), len(death_tensor)

(342, 549)

In [115]:
num = range(len(survived))
stacked_survived = [tensor(survived.iloc[num]) for num in num]

In [116]:
copydf = model_df

In [118]:
copydf = copydf.drop(columns=['Age_N', 'log_Fare', 'Ones', 'Linear', 'Loss'])

In [119]:
copydf['Embarked_C'].mean(), copydf['Embarked_S'].mean()

(0.1889763779527559, 0.7244094488188977)

In [120]:
# implement same logic for tensor stacked -- death here is still using 13 rows, need to update.aka next code block
r = [tensor(death.iloc[num]) for num in range(len(death))]
rStacked = torch.stack(r).float()
rStacked.shape
# this makes sense, 549 rows, single vector with (1x13rows) vs they had a rank 3 tensor

torch.Size([549, 13])

In [121]:
copydf['Embarked_S'] = copydf['Embarked_S'].fillna(0)
copydf['Embarked_C'] = copydf['Embarked_C'].fillna(0)
copydf

SibSp  Parch  Male  Embarked_C  Embarked_S  Pclass1  Pclass2  Survived
0        1      0     1         0.0         1.0        0        0         0
1        1      0     0         1.0         0.0        1        0         1
2        0      0     0         0.0         1.0        0        0         1
3        1      0     0         0.0         1.0        1        0         1
4        0      0     1         0.0         1.0        0        0         0
..     ...    ...   ...         ...         ...      ...      ...       ...
886      0      0     1         0.0         1.0        0        1         0
887      0      0     0         0.0         1.0        1        0         1
888      1      2     0         0.0         1.0        0        0         0
889      0      0     1         1.0         0.0        1        0         1
890      0      0     1         0.0         0.0        0        0         0

[891 rows x 8 columns]

In [122]:
# we now have a single tensor that was created from calling tensor over all of our labelled rows of data using tensor()
survived_label = copydf['Survived'] == 1
death_label = copydf['Survived'] == 0
survived = copydf.loc[survived_label]
# survived['Embarked_S'] = survived['Embarked_S'].fillna(0)
# survived['Embarked_C'] = survived['Embarked_C'].fillna(0)
death = copydf.loc[death_label]
# num = range(len(survived))
# nums = range(len(death))
stacked_survived = [tensor(survived.iloc[num]) for num in range(len(survived))]
stacked_death = [tensor(death.iloc[num]) for num in range(len(death))]
# stacked_survived.shape, stacked_death.shape
len(stacked_death), len(stacked_survived)


(549, 342)

In [123]:
# Combine all of the rows of tensors previously created into a single 2 dimensional tensor - we also want the average in each labelled stacked tensor here

# Divide by the number of deaths of survivors in each label?
survive_tensors_stacked = torch.stack(stacked_survived).float()
death_tensors_stacked = torch.stack(stacked_death).float()


# mean_survived = stacked_death.mean(0)
# mean_death = stacked_survived.mean(0)


In [124]:
survive_tensors_stacked.shape, death_tensors_stacked.shape # i.e. 2 x rank 2 tensors with each 342 & 549 labels respectively, consisting of 8 rows each

(torch.Size([342, 8]), torch.Size([549, 8]))

In [125]:
mean_survived = survive_tensors_stacked.mean(0)
mean_death = death_tensors_stacked.mean(0)

In [126]:
mean_survived,mean_death
# embarked rows are Nan - due to fillna?  -- no more

(tensor([0.4737, 0.4649, 0.3187, 0.2719, 0.6345, 0.3977, 0.2544, 1.0000]),
 tensor([0.5537, 0.3297, 0.8525, 0.1366, 0.7778, 0.1457, 0.1767, 0.0000]))

In [127]:
single_survivor = survive_tensors_stacked[1]
single_death = death_tensors_stacked[1]

single_death, single_survivor

(tensor([0., 0., 1., 0., 1., 0., 0., 0.]),
 tensor([0., 0., 0., 0., 1., 0., 0., 1.]))

In [128]:
import torch.nn.functional as F

In [129]:
# distance between survivor and meandeath tensor
F.l1_loss(single_survivor.float(),mean_death), F.mse_loss(single_survivor,mean_death).sqrt()

(tensor(0.4271), tensor(0.5318))

In [130]:
# distance between survivor and survivor tensor

F.l1_loss(single_survivor.float(),mean_survived), F.mse_loss(single_survivor,mean_survived).sqrt()
# need RElu given that data contains many 0? -- > nan output 

# Update - both values are smaller than the distance between the survivor and the mean of the death

(tensor(0.3183), tensor(0.3487))

In [131]:
def survive_distance(a,b): 
    return (a-b).abs().mean()
# distance_all_survived = survive_distance(survive_tensors_stacked, mean_survived)
# distance_all_survived
type(stacked_survived), type(mean_survived)

(list, torch.Tensor)

In [132]:
# calculate the distance for all of the survivors in the validation set compared to the valid_surivivors_tens object - i.e. Pytorch will use broadcasting given that the tensors are of different rank
valid_survivor_dist = survive_distance(survive_tensors_stacked, mean_survived)
valid_survivor_dist, valid_survivor_dist.shape

(tensor(0.4210), torch.Size([]))

In [133]:
# Create a function that to determine if the row is a survivor 
def is_alive(x): return survive_distance(x,mean_survived) < survive_distance(x,mean_death)

In [134]:
# Test it out -- the range here might not be the same given that this is for rows and not images of a rank 3 tensor with a hor and vert axixs
# Update - changed the -1,-2 to simple mean() to fix the index out of range
is_alive(single_survivor), is_alive(single_survivor).float
# function works, is a valid survivor

(tensor(True), <function Tensor.float>)

In [135]:
# Test our function on the whole validation set of survivors :
is_alive(survive_tensors_stacked)

tensor(True)

In [136]:
# Calculate the accuracy for each of the survivors and deaths by taking the average of that function for all survivors and its inverse for all deaths
accuracy_alive = is_alive(survive_tensors_stacked).float() .mean()
accuracy_death = (1 - is_alive(death_tensors_stacked).float()).mean()

accuracy_alive,accuracy_death,(accuracy_alive+accuracy_death)/2

(tensor(1.), tensor(1.), tensor(1.))

# Use Stochastic Gradient Descent to optimize our prediction model
1. Initialize the weights.
2. For each image, use these weights to predict whether it appears to be a 3 or a 7.
3. Based on these predictions, calculate how good the model is (its loss).
4. Calculate the gradient, which measures for each weight, how changing that weight would change the loss
5. Step (that is, change) all the weights based on that calculation.
6. Go back to the step 2, and repeat the process.
7. Iterate until we stop the training process 

In [137]:
# Simple quadractic function that will be used for SGD
def f(x): return x**2

# Get a tensor which will requre gradients
xt = tensor(3.).requires_grad_()
yt = f(xt)
yt.backward()
xt.grad

tensor(6.)

In [138]:
# Repeat the steps but with a vector argument 
xt = tensor([3.,4.,10.]).requires_grad_()
xt

# Add sum to the quadratic function so it can take a vector (rank-1 tensor) and return a scalar (rank-0 tensor)
def f(x): return (x**2).sum()

yt = f(xt)
yt

tensor(125., grad_fn=<SumBackward0>)

In [139]:
yt.backward()
xt.grad
# Implement stepping with a learning rate
lr = 1e-5
# w -= gradient(w) * lr


In [140]:
# Loss function that will be used in our parameters, and quadratic function that will be used to measure the inputs vs the functions parameters
def mse(preds, targets): return ((preds-targets)**2).mean()

def f(t, params):
    a,b,c = params
    return a*(t**2) + (b*t) + c

In [141]:
# 1
def init_params(size, std=1.0): return (torch.randn(size)*std).requires_grad_()


weights = init_params((8,1))
bias = init_params(1)

In [142]:
# get train x
train_x = torch.cat([survive_tensors_stacked, death_tensors_stacked]).view(-1, 8)
(train_x[0]*weights.T).sum() + bias

tensor([-1.1449], grad_fn=<AddBackward0>)

In [143]:
# TODO get validation data through kaggle and make it as a stacked tensor
def sigmoid(x): return 1/(1+torch.exp(-x))

def survive_loss_updated(predictions, targets):
    predictions = predictions.sigmoid()
    return torch.where(targets==1, 1-predictions, predictions).mean()

In [144]:
train_y = tensor([1]*len(survived) + [0]*len(death)).unsqueeze(1)

# dset =

dset = list(zip(train_x,train_y))
x,y = dset[0]
x.shape,y

# UPDATE DL SO THAT XB SHAPE AND YB SHAPE REFLECT WHAT WE WANT
dl = DataLoader(dset, batch_size=8)
xb,yb = first(dl)
xb.shape,yb.shape

(torch.Size([8, 8]), torch.Size([8, 1]))

In [145]:
twenty_percent_df = pd.read_csv('/kaggle/input/titanic-survival-dataset/train.csv')
twenty_percent_df['Male'] = twenty_percent_df['Sex']
twenty_percent_df['Male'] = twenty_percent_df['Male'].replace({'male': 1, 'female' : 0})
twenty_percent_df['Embarked_C'] = twenty_percent_df['Embarked']
twenty_percent_df['Embarked_C'] = twenty_percent_df['Embarked_C'].replace({'S':0, 'C':1, 'Q':0})
twenty_percent_df['Embarked_S'] = twenty_percent_df['Embarked']
twenty_percent_df['Embarked_S'] = twenty_percent_df['Embarked_S'].replace({'S':1, 'C':0, 'Q':0})
twenty_percent_df['Pclass1'] = twenty_percent_df['Pclass']
twenty_percent_df['Pclass2'] = twenty_percent_df['Pclass']
twenty_percent_df['Pclass1'] = twenty_percent_df['Pclass1'].replace({2:0, 3:0})
twenty_percent_df['Pclass2'] = twenty_percent_df['Pclass2'].replace({1:0, 3:0, 2:1})
twenty_percent_df = twenty_percent_df.drop(columns=['Sex', 'Age', 'Fare', 'Embarked', 'Pclass'])
twenty_percent_df['Embarked_S'] = twenty_percent_df['Embarked_S'].fillna(0)
twenty_percent_df['Embarked_C'] = twenty_percent_df['Embarked_C'].fillna(0)
twenty_percent_df = twenty_percent_df.drop(columns=['Name', 'Cabin', 'PassengerId', 'Ticket'])
eighty_percent_df = twenty_percent_df.iloc[180:]
twenty_percent_df = twenty_percent_df.iloc[:179]


In [146]:
# labels for both training and validation data

#training
survived_label_train = eighty_percent_df['Survived'] == 1
death_label_train = eighty_percent_df['Survived'] == 0
survived_train = eighty_percent_df.loc[survived_label_train]
death_train = eighty_percent_df.loc[death_label_train]
stacked_survived_train = [tensor(survived_train.iloc[num]) for num in range(len(survived_train))]
stacked_death_train = [tensor(death_train.iloc[num]) for num in range(len(death_train))]

#stack
survive_tensors_stacked_train = torch.stack(stacked_survived_train).float()
death_tensors_stacked_train = torch.stack(stacked_death_train).float()

#validation
survived_label_validation = twenty_percent_df['Survived'] == 1
death_label_validation = twenty_percent_df['Survived'] == 0
survived_validation = twenty_percent_df.loc[survived_label_validation]
death_validation = twenty_percent_df.loc[death_label_validation]
stacked_survived_validation = [tensor(survived_validation.iloc[num]) for num in range(len(survived))]
stacked_death_validation = [tensor(death_validation.iloc[num]) for num in range(len(death))]

#stack
survive_tensors_stacked_validation = torch.stack(stacked_survived_validation).float()
death_tensors_stacked_validation = torch.stack(stacked_death_validation).float()



In [149]:
# create the stacked tensors for both training data and validation data

# create training dl
train_x = torch.cat([survive_tensors_stacked_train, death_tensors_stacked_train]).view(-1, 8)
train_y = tensor([1]*len(survived) + [0]*len(death)).unsqueeze(1)
dset = list(zip(train_x,train_y))
dl = DataLoader(dset, batch_size=8)

# create validation dl
valid_x = torch.cat([survive_tensors_stacked_validation, death_tensors_stacked_validation]).view(-1, 8)
valid_y = tensor([1]*len(survive_tensors_stacked_validation) + [0]*len(death_tensors_stacked_validation)).unsqueeze(1)
valid_dset = list(zip(valid_x,valid_y))
valid_dl = DataLoader(valid_dset, batch_size=8)

# finally
dls = DataLoaders(dl, valid_dl)

def batch_accuracy(xb, yb):
    preds = xb.sigmoid()
    correct = (preds>0.5) == yb
    return correct.float().mean()

# neural net
simple_net = nn.Sequential(
    nn.Linear(8,1),
    nn.ReLU(),
    nn.Linear(1,8)
)


learn = Learner(dls, simple_net, opt_func=SGD,
                loss_func=survive_loss_updated, metrics=batch_accuracy)

learn.fit(40, 0.1)

In [166]:
# same for the validation set 

validdf = pd.read_csv('/kaggle/input/test-titanic/test.csv')
validdf['Male'] = validdf['Sex']
validdf['Male'] = validdf['Male'].replace({'male': 1, 'female' : 0})
validdf['Embarked_C'] = validdf['Embarked']
validdf['Embarked_C'] = validdf['Embarked_C'].replace({'S':0, 'C':1, 'Q':0})
validdf['Embarked_S'] = validdf['Embarked']
validdf['Embarked_S'] = validdf['Embarked_S'].replace({'S':1, 'C':0, 'Q':0})
validdf['Pclass1'] = validdf['Pclass']
validdf['Pclass2'] = validdf['Pclass']
validdf['Pclass1'] = validdf['Pclass1'].replace({2:0, 3:0})
validdf['Pclass2'] = validdf['Pclass2'].replace({1:0, 3:0, 2:1})
validdf['Embarked_S'] = validdf['Embarked_S'].fillna(0)
validdf['Embarked_C'] = validdf['Embarked_C'].fillna(0)



validdf

PassengerId  Pclass                                          Name  \
0            892       3                              Kelly, Mr. James   
1            893       3              Wilkes, Mrs. James (Ellen Needs)   
2            894       2                     Myles, Mr. Thomas Francis   
3            895       3                              Wirz, Mr. Albert   
4            896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)   
..           ...     ...                                           ...   
413         1305       3                            Spector, Mr. Woolf   
414         1306       1                  Oliva y Ocana, Dona. Fermina   
415         1307       3                  Saether, Mr. Simon Sivertsen   
416         1308       3                           Ware, Mr. Frederick   
417         1309       3                      Peter, Master. Michael J   

        Sex   Age  SibSp  Parch              Ticket      Fare Cabin Embarked  \
0      male  34.5      0      0              330911    7.8292   NaN        Q   
1    female  47.0      1      0              363272    7.0000   NaN        S   
2      male  62.0      0      0              240276    9.6875   NaN        Q   
3      male  27.0      0      0              315154    8.6625   NaN        S   
4    female  22.0      1      1             3101298   12.2875   NaN        S   
..      ...   ...    ...    ...                 ...       ...   ...      ...   
413    male   NaN      0      0           A.5. 3236    8.0500   NaN        S   
414  female  39.0      0      0            PC 17758  108.9000  C105        C   
415    male  38.5      0      0  SOTON/O.Q. 3101262    7.2500   NaN        S   
416    male   NaN      0      0              359309    8.0500   NaN        S   
417    male   NaN      1      1                2668   22.3583   NaN        C   

     Male  Embarked_C  Embarked_S  Pclass1  Pclass2  
0       1           0           0        0        0  
1       0           0           1        0        0  
2       1           0           0        0        1  
3       1           0           1        0        0  
4       0           0           1        0        0  
..    ...         ...         ...      ...      ...  
413     1           0           1        0        0  
414     0           1           0        1        0  
415     1           0           1        0        0  
416     1           0           1        0        0  
417     1           1           0        0        0  

[418 rows x 16 columns]

In [167]:
#hide
# maxAge, maxFare = max(validdf['Age']), max(validdf['Fare'])
# validdf['Age_N'] = validdf['Age'] / maxAge
# validdf['log_Fare'] = validdf['Fare'] / maxFare
# validdf['log_Fare'] = np.log10(df['log_Fare'] + 1)

# model_df['Survived'] = df['Survived']
validdf = validdf.drop(columns=['Sex', 'Age', 'Fare', 'Embarked', 'Pclass'])
# model_df['Age_N'] = model_df['Age_N'].fillna(0)


# copydf = model_df
# copydf = copydf.drop(columns=['Age_N', 'log_Fare', 'Ones', 'Linear', 'Loss'])
validdf['Embarked_S'] = validdf['Embarked_S'].fillna(0)
validdf['Embarked_C'] = validdf['Embarked_C'].fillna(0)

# we now have a single tensor that was created from calling tensor over all of our labelled rows of data using tensor()
# survived_label_valid = validdf['Survived'] == 1
# death_label_valid = validdf['Survived'] == 0
# survived_valid = validdf.loc[survived_label]
# survived['Embarked_S'] = survived['Embarked_S'].fillna(0)
# survived['Embarked_C'] = survived['Embarked_C'].fillna(0)
# death_valid = validdf.loc[death_label]
# num = range(len(survived))
# nums = range(len(death))
# stacked_pass_valid = [tensor(validdf.iloc[num]) for num in range(len(validdf))]
# stacked_death_valid = [tensor(death_valid.iloc[num]) for num in range(len(death_valid))]
# stacked_survived.shape, stacked_death.shape
# len(stacked_death_valid), len(stacked_survived_valid)


TypeError: can't convert np.ndarray of type numpy.object_. The only supported types are: float64, float32, float16, complex64, complex128, int64, int32, int16, int8, uint8, and bool.

In [168]:
validdf['Embarked_S'] = validdf['Embarked_S'].fillna(0)
validdf['Embarked_C'] = validdf['Embarked_C'].fillna(0)
validdf = validdf.drop(columns=['Name', 'Cabin', 'PassengerId', 'Ticket'])

In [169]:
stacked_pass_valid = [tensor(validdf.iloc[num]) for num in range(len(validdf))]

In [170]:
validdf

SibSp  Parch  Male  Embarked_C  Embarked_S  Pclass1  Pclass2
0        0      0     1           0           0        0        0
1        1      0     0           0           1        0        0
2        0      0     1           0           0        0        1
3        0      0     1           0           1        0        0
4        1      1     0           0           1        0        0
..     ...    ...   ...         ...         ...      ...      ...
413      0      0     1           0           1        0        0
414      0      0     0           1           0        1        0
415      0      0     1           0           1        0        0
416      0      0     1           0           1        0        0
417      1      1     1           1           0        0        0

[418 rows x 7 columns]

In [171]:
# diff between tensor and torch.cat ? VALID DSET IS THE OBJECT THAT WILL ULTIMATELY BE IN THE LEARNER
valid_x = torch.cat([survive_tensors_stacked, death_tensors_stacked]).view(-1, 8)
valid_y = tensor([1]*len(survive_tensors_stacked) + [0]*len(death_tensors_stacked)).unsqueeze(1)
valid_dset = list(zip(valid_x,valid_y))
valid_dl = DataLoader(valid_dset, batch_size=418)

# need both dl, valid dl and dl
# then 
linear_model = nn.Linear(8,1)
opt = SGD(linear_model.parameters(), lr)
# train_model(linear_model, 20)
#pass in the training and validatin data here
dls = DataLoaders(dl, valid_dl)
#finally 

# batch accuracy is optional 
def batch_accuracy(xb, yb):
    preds = xb.sigmoid()
    correct = (preds>0.5) == yb
    return correct.float().mean()

learn = Learner(dls, nn.Linear(8,1), opt_func=SGD,
                loss_func=survive_loss_updated, metrics=batch_accuracy)

learn.fit(10, lr=lr)



In [173]:
# update the learner as a Neural Network
simple_net = nn.Sequential(
    nn.Linear(8,1),
    nn.ReLU(),
    nn.Linear(1,8)
)


learn = Learner(dls, simple_net, opt_func=SGD,
                loss_func=survive_loss_updated, metrics=batch_accuracy)

learn.fit(30, 0.1)

In [174]:

learn.recorder.values[-1][2]

1.0